/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#0c1420",
        "tertiary-container": "#1eed9f",
        "on-secondary": "#003064",
        "secondary-fixed": "#d6e3ff",
        "on-error-container": "#ffdad6",
        "secondary": "#aac7ff",
        "background": "#0c1420",
        "surface-tint": "#00daf3",
        "on-error": "#690005",
        "on-primary-container": "#00626e",
        "on-secondary-container": "#002957",
        "surface-bright": "#323947",
        "outline": "#849396",
        "surface-container-high": "#232a37",
        "surface-variant": "#2d3542",
        "on-primary-fixed-variant": "#004f58",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "inverse-surface": "#dbe3f4",
        "surface-dim": "#0c1420",
        "tertiary-fixed": "#4dffb1",
        "tertiary": "#a9ffce",
        "secondary-fixed-dim": "#aac7ff",
        "on-background": "#dbe3f4",
        "on-primary-fixed": "#001f24",
        "tertiary-fixed-dim": "#00e296",
        "primary-fixed-dim": "#00daf3",
        "outline-variant": "#3b494c",
        "on-tertiary-fixed-variant": "#005233",
        "on-surface": "#dbe3f4",
        "on-surface-variant": "#bac9cc",
        "surface-container-highest": "#2d3542",
        "surface-container-lowest": "#070e1a",
        "primary": "#c3f5ff",
        "on-tertiary-container": "#006642",
        "primary-container": "#00e5ff",
        "primary-fixed": "#9cf0ff",
        "inverse-on-surface": "#29313e",
        "on-tertiary": "#003822",
        "surface-container": "#18202c",
        "on-secondary-fixed-variant": "#00468d",
        "on-secondary-fixed": "#001b3e",
        "on-primary": "#00363d",
        "surface-container-low": "#141c28",
        "inverse-primary": "#006875",
        "on-tertiary-fixed": "#002112",
        "secondary-container": "#3e90ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-xs": "0.25rem",
        "margin-lg": "3rem",
        "space-lg": "1.5rem",
        "gutter-lg": "2rem",
        "gutter-md": "1.5rem",
        "space-xl": "2.5rem",
        "margin": "1rem",
        "margin-md": "2rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "gutter": "1rem"
      },
      fontFamily: {
        sans: ["Geist", "Inter", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        mono: ["JetBrains Mono", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
        "telemetry-metric": ["JetBrains Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"],
        "headline-lg": ["Geist", "Inter", "system-ui", "sans-serif"],
        "body-sm": ["Geist", "Inter", "system-ui", "sans-serif"],
        "label-sm": ["JetBrains Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"],
        "body-lg": ["Geist", "Inter", "system-ui", "sans-serif"],
        "headline-md": ["Geist", "Inter", "system-ui", "sans-serif"],
        "display": ["Geist", "Inter", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Geist", "Inter", "system-ui", "sans-serif"],
        "body-md": ["Geist", "Inter", "system-ui", "sans-serif"],
        "label-md": ["JetBrains Mono", "SFMono-Regular", "Menlo", "Consolas", "monospace"],
        "headline-sm": ["Geist", "Inter", "system-ui", "sans-serif"]
      },
      fontSize: {
        "telemetry-metric": ["2rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-lg": ["2.25rem", { "lineHeight": "2.75rem", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["0.75rem", { "lineHeight": "1rem", "fontWeight": "400" }],
        "label-sm": ["0.6875rem", { "lineHeight": "0.875rem", "letterSpacing": "0.06em", "fontWeight": "500" }],
        "body-lg": ["1rem", { "lineHeight": "1.5rem", "fontWeight": "400" }],
        "headline-md": ["1.5rem", { "lineHeight": "2rem", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "display": ["3.5rem", { "lineHeight": "4rem", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "headline-lg-mobile": ["1.75rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-md": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "400" }],
        "label-md": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "headline-sm": ["1.125rem", { "lineHeight": "1.5rem", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
};
